### ISSUE TITLE
OMS Ruby Resource Error 1.11.0-9

### ISSUE THREAD

**Issue by cj-anthony** [microsoft/OMS-Agent-for-Linux#1034]
Currently having an issue with the latest version of OMS on Centos 6.10. After the service starts I get this error whenever it tries to monitor the VM.

I have searched the issues and no one seems to have had this issue before. Does anyone know how I might troubleshoot it.

> 2019-09-05 07:52:30 +1000 [error]: unexpected error error_class=ThreadError error=#<ThreadError: can't create Thread: Resource temporarily unavailable>
  > 2019-09-05 07:52:30 +1000 [error]: /opt/microsoft/omsagent/plugin/in_wlm_oms_omi.rb:33:in `initialize'
  > 2019-09-05 07:52:30 +1000 [error]: /opt/microsoft/omsagent/plugin/in_wlm_oms_omi.rb:33:in `new'
  > 2019-09-05 07:52:30 +1000 [error]: /opt/microsoft/omsagent/plugin/in_wlm_oms_omi.rb:33:in `start'
  > 2019-09-05 07:52:30 +1000 [error]: /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/root_agent.rb:115:in `block in start'
  > 2019-09-05 07:52:30 +1000 [error]: /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/root_agent.rb:114:in `each'
  > 2019-09-05 07:52:30 +1000 [error]: /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/root_agent.rb:114:in `start'
  > 2019-09-05 07:52:30 +1000 [error]: /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/engine.rb:237:in `start'
  > 2019-09-05 07:52:30 +1000 [error]: /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/engine.rb:187:in `run'
  > 2019-09-05 07:52:30 +1000 [error]: /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/supervisor.rb:564:in `run_engine'
  > 2019-09-05 07:52:30 +1000 [error]: /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/supervisor.rb:170:in `block in start'
  > 2019-09-05 07:52:30 +1000 [error]: /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/supervisor.rb:360:in `main_process'
  > 2019-09-05 07:52:30 +1000 [error]: /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/supervisor.rb:164:in `start'
  > 2019-09-05 07:52:30 +1000 [error]: /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/command/fluentd.rb:173:in `<top (required)>'
  > 2019-09-05 07:52:30 +1000 [error]: /opt/microsoft/omsagent/ruby/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  > 2019-09-05 07:52:30 +1000 [error]: /opt/microsoft/omsagent/ruby/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  > 2019-09-05 07:52:30 +1000 [error]: /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/bin/fluentd:5:in `<top (required)>'
  > 2019-09-05 07:52:30 +1000 [error]: /opt/microsoft/omsagent/bin/omsagent-79953964-8b4b-4a2c-8edc-4766fc59a5fd:22:in `load'
  > 2019-09-05 07:52:30 +1000 [error]: /opt/microsoft/omsagent/bin/omsagent-79953964-8b4b-4a2c-8edc-4766fc59a5fd:22:in `<main>'
> 2019-09-05 07:52:30 +1000 [info]: shutting down fluentd
> 2019-09-05 07:52:30 +1000 [error]: unexpected error error="can't create Thread: Resource temporarily unavailable"
  > 2019-09-05 07:52:30 +1000 [error]: /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/root_agent.rb:123:in `initialize'
  > 2019-09-05 07:52:30 +1000 [error]: /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/root_agent.rb:123:in `new'
  > 2019-09-05 07:52:30 +1000 [error]: /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/root_agent.rb:123:in `block in shutdown'
  > 2019-09-05 07:52:30 +1000 [error]: /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/root_agent.rb:122:in `map'
  > 2019-09-05 07:52:30 +1000 [error]: /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/root_agent.rb:122:in `shutdown'
  > 2019-09-05 07:52:30 +1000 [error]: /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/engine.rb:241:in `shutdown'
  > 2019-09-05 07:52:30 +1000 [error]: /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/engine.rb:212:in `run'
  > 2019-09-05 07:52:30 +1000 [error]: /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/supervisor.rb:564:in `run_engine'
  > 2019-09-05 07:52:30 +1000 [error]: /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/supervisor.rb:170:in `block in start'
  > 2019-09-05 07:52:30 +1000 [error]: /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/supervisor.rb:360:in `main_process'
  > 2019-09-05 07:52:30 +1000 [error]: /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/supervisor.rb:164:in `start'
  > 2019-09-05 07:52:30 +1000 [error]: /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/command/fluentd.rb:173:in `<top (required)>'
  > 2019-09-05 07:52:30 +1000 [error]: /opt/microsoft/omsagent/ruby/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  > 2019-09-05 07:52:30 +1000 [error]: /opt/microsoft/omsagent/ruby/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  > 2019-09-05 07:52:30 +1000 [error]: /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/bin/fluentd:5:in `<top (required)>'
  > 2019-09-05 07:52:30 +1000 [error]: /opt/microsoft/omsagent/bin/omsagent-79953964-8b4b-4a2c-8edc-4766fc59a5fd:22:in `load'
  > 2019-09-05 07:52:30 +1000 [error]: /opt/microsoft/omsagent/bin/omsagent-79953964-8b4b-4a2c-8edc-4766fc59a5fd:22:in `<main>'

**Comment by cj-anthony** [comment]
Closing this, the issue was that there was an old OMS binary on the drive and the installer was picking up that.
