### ISSUE TITLE
Onboarding problem, creating a certificate error code 400

### ISSUE THREAD

**Issue by rjcrystal** [Microsoft/OMS-Agent-for-Linux#106]
during onboarding via omsadmin.sh i got this error 
```
-e info Generating certificate ...
/opt/microsoft/omsagent/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': /opt/microsoft/omsagent/ruby/lib/ruby/2.2.0/x86_64-linux/openssl.so: undefined symbol: SSLv3_method - /opt/microsoft/omsagent/ruby/lib/ruby/2.2.0/x86_64-linux/openssl.so (LoadError)
        from /opt/microsoft/omsagent/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/microsoft/omsagent/ruby/lib/ruby/2.2.0/openssl.rb:17:in `<top (required)>'
        from /opt/microsoft/omsagent/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/microsoft/omsagent/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/microsoft/omsagent/bin/auth_key.rb:2:in `<main>'
-e error        Error onboarding. HTTP code 400

```
and during onboarding via omsagent-onboard.conf i got this error 

```
● omsagent.service - Operations Management Suite agent
   Loaded: loaded (/lib/systemd/system/omsagent.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2016-06-12 02:38:17 UTC; 7s ago
  Process: 4686 ExecStop=/bin/rm -f /var/opt/microsoft/omsagent/run/omsagent.pid (code=exited, status=0/SUCCESS)
  Process: 4678 ExecStart=/opt/microsoft/omsagent/bin/omsagent -d /var/opt/microsoft/omsagent/run/omsagent.pid -o /var/opt/microsoft/omsagent/log/omsagent.log --no-supervisor (code=exited, status=1/FAILURE)
 Main PID: 4678 (code=exited, status=1/FAILURE)

Jun 12 02:38:17 nales omsagent[4678]: from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.12.14/lib/fluent/supervisor.rb:485:in `init_engine'
Jun 12 02:38:17 nales omsagent[4678]: from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.12.14/lib/fluent/supervisor.rb:153:in `block in start'
Jun 12 02:38:17 nales omsagent[4678]: from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.12.14/lib/fluent/supervisor.rb:306:in `call'
Jun 12 02:38:17 nales omsagent[4678]: from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.12.14/lib/fluent/supervisor.rb:306:in `main_process'
Jun 12 02:38:17 nales omsagent[4678]: from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.12.14/lib/fluent/supervisor.rb:151:in `start'
Jun 12 02:38:17 nales omsagent[4678]: from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.12.14/lib/fluent/command/fluentd.rb:167:in `<top (required)>'
Jun 12 02:38:17 nales omsagent[4678]: from /opt/microsoft/omsagent/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
Jun 12 02:38:17 nales systemd[1]: omsagent.service: main process exited, code=exited, status=1/FAILURE
Jun 12 02:38:17 nales systemd[1]: Unit omsagent.service entered failed state.
Jun 12 02:38:17 nales systemd[1]: omsagent.service failed.
```

**Comment by jeffaco** [comment]
@rjcrystal - I wonder if this relates to issue #14, which was pretty similar to this.

What machine is this occurring on (distribution/version)? Are you using the standard version of OpenSSL that ships on the machine or did you try to replace it with some different version?

Please look over issue #14 and let us know if that applies to you, thanks!

**Comment by rjcrystal** [comment]
Hey @jeffaco i use ubuntu 15.04 open ssl version OpenSSL 1.0.2f  28 Jan 2016 
more on that 
```
OpenSSL 1.0.2f  28 Jan 2016
built on: reproducible build, date unspecified
platform: debian-amd64
options:  bn(64,64) rc4(16x,int) des(idx,cisc,16,int) blowfish(idx)
compiler: gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -m64 -DL_ENDIAN -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wa,--noexecstack -Wall -DMD32_REG_T=int -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
OPENSSLDIR: "/usr/lib/ssl"
```

**Comment by jeffaco** [comment]
Hi @rjcrystal My answer is going to smell bad, and I apologize for that! 😦 

Ubuntu 15.04 support dropped in February, 2016, so Ubuntu no longer supports it. Furthermore,  Canonical identified this problem and resolved it, because we have no such issue in Ubuntu 16.04 (which has the benefit of being an LTS release).

The workaround is to build OMS from source, which would allow you to customize to the version of SSL on the system. But we still don't have OMI opened up yet - it's still private (sigh), which makes building from source rather challenging.

The easy (and rather flippant - again, I apologize) answer is: "Please move to Ubuntu 16.04, and you'll be fine".

If this is not possible for you, and you really NEED to run on Ubuntu 15.04, I can try to document a procedure for you to build from source on your system. If you can wait until late summer, however, I'm quite confident that OMI will be public by then, significantly simplifying the process to build from source.

Please let me know how you'd like to proceed, thanks.

**Comment by rjcrystal** [comment]
Hey @jeffaco Thanks for letting me know. i was afraid this might me the issue. Its not possible but we'll be moving to ubuntu 16.04 soon. and i think till then omi will get out of preview. and i can try it out.
Thanks for the quick reply. :smile:

**Comment by jeffaco** [comment]
Hi @rjcrystal No problem, thanks I could help.

I'm going to close this issue. If you have further issues, please feel free to reach out to me.

**Comment by rjcrystal** [comment]
Hi @jeffaco i  tried with ubuntu 16.04 works fine :smile: but when i try with ubuntu 14.04 with even newer version of openssl it gives boot error in ruby jem.
```
Linux #### 4.4.0-34-generic #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
OpenSSL 1.0.2g-fips  1 Mar 2016
built on: reproducible build, date unspecified
platform: debian-amd64
options:  bn(64,64) rc4(16x,int) des(idx,cisc,16,int) blowfish(idx) 
compiler: cc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -m64 -DL_ENDIAN -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wa,--noexecstack -Wall -DMD32_REG_T=int -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
OPENSSLDIR: "/usr/lib/ssl"

```
``` 
Linux ##### 3.19.0-37-generic #42~14.04.1-Ubuntu SMP Mon Nov 23 15:13:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

OpenSSL 1.0.2h  3 May 2016
built on: reproducible build, date unspecified
platform: debian-amd64
options:  bn(64,64) rc4(16x,int) des(idx,cisc,16,int) blowfish(idx) 
compiler: gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -m64 -DL_ENDIAN -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wa,--noexecstack -Wall -DMD32_REG_T=int -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
OPENSSLDIR: "/usr/lib/ssl"

```

error 
```
$ sudo service omsagent start
 * Starting Operations Management Suite agent:                                                                                                                          /opt/microsoft/omsagent/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': /opt/microsoft/omsagent/ruby/lib/ruby/2.2.0/x86_64-linux/openssl.so: undefined symbol: SSLv3_method - /opt/microsoft/omsagent/ruby/lib/ruby/2.2.0/x86_64-linux/openssl.so (LoadError)
	from /opt/microsoft/omsagent/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/microsoft/omsagent/ruby/lib/ruby/2.2.0/openssl.rb:17:in `<top (required)>'
	from /opt/microsoft/omsagent/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/microsoft/omsagent/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/microsoft/omsagent/ruby/lib/ruby/2.2.0/net/https.rb:22:in `<top (required)>'
	from /opt/microsoft/omsagent/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/microsoft/omsagent/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/microsoft/omsagent/plugin/oms_common.rb:11:in `<class:Common>'
	from /opt/microsoft/omsagent/plugin/oms_common.rb:8:in `<module:OMS>'
	from /opt/microsoft/omsagent/plugin/oms_common.rb:1:in `<top (required)>'
	from /opt/microsoft/omsagent/plugin/changetracking_lib.rb:6:in `require_relative'
	from /opt/microsoft/omsagent/plugin/changetracking_lib.rb:6:in `<top (required)>'
	from /opt/microsoft/omsagent/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/microsoft/omsagent/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.12.24/lib/fluent/plugin.rb:89:in `block in load_plugin_dir'
	from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.12.24/lib/fluent/plugin.rb:87:in `each'
	from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.12.24/lib/fluent/plugin.rb:87:in `load_plugin_dir'
	from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.12.24/lib/fluent/engine.rb:138:in `load_plugin_dir'
	from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.12.24/lib/fluent/supervisor.rb:513:in `block in init_engine'
	from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.12.24/lib/fluent/supervisor.rb:510:in `each'
	from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.12.24/lib/fluent/supervisor.rb:510:in `init_engine'
	from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.12.24/lib/fluent/supervisor.rb:166:in `block in start'
	from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.12.24/lib/fluent/supervisor.rb:360:in `call'
	from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.12.24/lib/fluent/supervisor.rb:360:in `main_process'
	from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.12.24/lib/fluent/supervisor.rb:164:in `start'
	from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.12.24/lib/fluent/command/fluentd.rb:173:in `<top (required)>'
	from /opt/microsoft/omsagent/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /opt/microsoft/omsagent/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.12.24/bin/fluentd:5:in `<top (required)>'
	from /opt/microsoft/omsagent/bin/omsagent:23:in `load'
	from /opt/microsoft/omsagent/bin/omsagent:23:in `<main>'

```
this is very weird, any ideas what is happening here ?
