### ISSUE TITLE
unexpected error error="Fluent::SCOMTimerFilterPlugin: default value specified twice for time_interval"

### ISSUE THREAD

**Issue by zlonok** [microsoft/OMS-Agent-for-Linux#1194]
I have an error starting the omsagent

```
2020-05-26 09:31:49 +0200 [info]: reading config file path="/etc/opt/microsoft/omsagent/scom/conf/omsagent.conf"
2020-05-26 09:31:49 +0200 [info]: starting fluentd-0.12.40 without supervision
2020-05-26 09:31:49 +0200 [error]: unexpected error error="Fluent::SCOMTimerFilterPlugin: default value specified twice for time_interval"
  2020-05-26 09:31:49 +0200 [error]: /local/opt/microsoft/omsagent/ruby/lib/ruby/gems/2.4.0/gems/fluentd-0.12.40/lib/fluent/config/configure_proxy.rb:218:in `config_set_default'
  2020-05-26 09:31:49 +0200 [error]: /local/opt/microsoft/omsagent/ruby/lib/ruby/gems/2.4.0/gems/fluentd-0.12.40/lib/fluent/config/configure_proxy.rb:177:in `parameter_configuration'
  2020-05-26 09:31:49 +0200 [error]: /local/opt/microsoft/omsagent/ruby/lib/ruby/gems/2.4.0/gems/fluentd-0.12.40/lib/fluent/config/configure_proxy.rb:202:in `config_param'
  2020-05-26 09:31:49 +0200 [error]: /local/opt/microsoft/omsagent/ruby/lib/ruby/gems/2.4.0/gems/fluentd-0.12.40/lib/fluent/configurable.rb:102:in `config_param'
  2020-05-26 09:31:49 +0200 [error]: /opt/microsoft/omsagent/plugin/scom_common.rb:128:in `<class:SCOMTimerFilterPlugin>'
  2020-05-26 09:31:49 +0200 [error]: /opt/microsoft/omsagent/plugin/scom_common.rb:125:in `<module:Fluent>'
  2020-05-26 09:31:49 +0200 [error]: /opt/microsoft/omsagent/plugin/scom_common.rb:123:in `<top (required)>'
  2020-05-26 09:31:49 +0200 [error]: /local/opt/microsoft/omsagent/ruby/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2020-05-26 09:31:49 +0200 [error]: /local/opt/microsoft/omsagent/ruby/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2020-05-26 09:31:49 +0200 [error]: /local/opt/microsoft/omsagent/ruby/lib/ruby/gems/2.4.0/gems/fluentd-0.12.40/lib/fluent/plugin.rb:89:in `block in load_plugin_dir'
  2020-05-26 09:31:49 +0200 [error]: /local/opt/microsoft/omsagent/ruby/lib/ruby/gems/2.4.0/gems/fluentd-0.12.40/lib/fluent/plugin.rb:87:in `each'
  2020-05-26 09:31:49 +0200 [error]: /local/opt/microsoft/omsagent/ruby/lib/ruby/gems/2.4.0/gems/fluentd-0.12.40/lib/fluent/plugin.rb:87:in `load_plugin_dir'
  2020-05-26 09:31:49 +0200 [error]: /local/opt/microsoft/omsagent/ruby/lib/ruby/gems/2.4.0/gems/fluentd-0.12.40/lib/fluent/engine.rb:138:in `load_plugin_dir'
  2020-05-26 09:31:49 +0200 [error]: /local/opt/microsoft/omsagent/ruby/lib/ruby/gems/2.4.0/gems/fluentd-0.12.40/lib/fluent/supervisor.rb:519:in `block in init_engine'
  2020-05-26 09:31:49 +0200 [error]: /local/opt/microsoft/omsagent/ruby/lib/ruby/gems/2.4.0/gems/fluentd-0.12.40/lib/fluent/supervisor.rb:516:in `each'
  2020-05-26 09:31:49 +0200 [error]: /local/opt/microsoft/omsagent/ruby/lib/ruby/gems/2.4.0/gems/fluentd-0.12.40/lib/fluent/supervisor.rb:516:in `init_engine'
  2020-05-26 09:31:49 +0200 [error]: /local/opt/microsoft/omsagent/ruby/lib/ruby/gems/2.4.0/gems/fluentd-0.12.40/lib/fluent/supervisor.rb:172:in `block in start'
  2020-05-26 09:31:49 +0200 [error]: /local/opt/microsoft/omsagent/ruby/lib/ruby/gems/2.4.0/gems/fluentd-0.12.40/lib/fluent/supervisor.rb:366:in `main_process'
  2020-05-26 09:31:49 +0200 [error]: /local/opt/microsoft/omsagent/ruby/lib/ruby/gems/2.4.0/gems/fluentd-0.12.40/lib/fluent/supervisor.rb:170:in `start'
  2020-05-26 09:31:49 +0200 [error]: /local/opt/microsoft/omsagent/ruby/lib/ruby/gems/2.4.0/gems/fluentd-0.12.40/lib/fluent/command/fluentd.rb:173:in `<top (required)>'
  2020-05-26 09:31:49 +0200 [error]: /local/opt/microsoft/omsagent/ruby/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2020-05-26 09:31:49 +0200 [error]: /local/opt/microsoft/omsagent/ruby/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2020-05-26 09:31:49 +0200 [error]: /local/opt/microsoft/omsagent/ruby/lib/ruby/gems/2.4.0/gems/fluentd-0.12.40/bin/fluentd:5:in `<top (required)>'
  2020-05-26 09:31:49 +0200 [error]: /opt/microsoft/omsagent/bin/omsagent:23:in `load'
  2020-05-26 09:31:49 +0200 [error]: /opt/microsoft/omsagent/bin/omsagent:23:in `<main>'
```
Server : RHEL 7.8

What could be the cause of this error?

Thanks.

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
