### ISSUE TITLE
platform.linux_distribution is removed in Python 3.8

### ISSUE THREAD

**Issue by emilguden** [microsoft/OMS-Agent-for-Linux#1288]
Hi,

Trying to run the troubleshooter on a Ubuntu 20.04
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"

And getting the below error:
```
CHECKING INSTALLATION...
Checking if running a supported OS version...
Traceback (most recent call last):
  File "/opt/microsoft/omsagent/tst/modules/helpers.py", line 65, in get_os_version
    (vm_dist, vm_ver, vm_id) = platform.linux_distribution()
AttributeError: module 'platform' has no attribute 'linux_distribution'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/microsoft/omsagent/tst/modules/main.py", line 254, in <module>
    run_troubleshooter()
  File "/opt/microsoft/omsagent/tst/modules/main.py", line 204, in run_troubleshooter
    success = section(interactive=interactive_mode)
  File "/opt/microsoft/omsagent/tst/modules/main.py", line 58, in check_all
    checked_install = check_installation(interactive)
  File "/opt/microsoft/omsagent/tst/modules/install/install.py", line 111, in check_installation
    checked_os = check_os()
  File "/opt/microsoft/omsagent/tst/modules/install/check_os.py", line 87, in check_os
    vm_info = get_os_version()
  File "/opt/microsoft/omsagent/tst/modules/helpers.py", line 67, in get_os_version
    (vm_dist, vm_ver, vm_id) = platform.dist()
AttributeError: module 'platform' has no attribute 'dist'

```
According to this [link](https://github.com/saltstack/salt/issues/37070)
platform.linux_distribution is removed from Python 3.8

I'm I missing something or do we need an update of the troubleshooter?

Before I found this repo I posted the same issue on the docs article: [Link](https://github.com/MicrosoftDocs/azure-docs/issues/67768)

Thanks!

**Comment by emilguden** [comment]
Any update on this?

**Comment by pranavperfect** [comment]
Wondering if any work is being done on this?

**Comment by Fairchild110** [comment]
I think I am running into the same issue, and I had to make an alias for python3 to python for the agent to install correctly.

**Comment by emilguden** [comment]
> I think I am running into the same issue, and I had to make an alias for python3 to python for the agent to install correctly.
 
Thank you!! I'll definitely take another look at this. Didn't find any other solution so thank you for posting :)

**Comment by dwilliams-dmu** [comment]
I am having the same issue.  This was reported in December of last year and M$ hasn't even given an update?  Clearly they haven't fixed it.

**Comment by stochastictalk** [comment]
Same issue here, maybe Microsoft are working on a troubleshooter for the troubleshooter

**Comment by pentiumoverdrive** [comment]
Encountered the same issue when I had problems with it connecting to my workspace.

As 2.7 was installed, you can start the troubleshooter using:

`python2.7 /opt/microsoft/omsagent/tst/modules/main.py`

**Comment by wasuaje** [comment]
Any update on this????? IT's important guys! as python 3.8 is widely used right now!

**Comment by coreyman2000** [comment]
updates on this?

**Comment by dwilliams-dmu** [comment]
This is not at all helpful but the complete lack of any effort from M$ on this has led me to believe it is simply not a tenable solution and have torn it out.  Quite frankly I'm surprised there isn't a light weight OVA or container that could just do this.  It would be in M$ best interest to get people's data into their platform.

**Comment by coreyman2000** [comment]
so turns out its been updated but not on the latest release yet, 

i just updated the one helper script and its working ok now

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
