### ISSUE TITLE
troubleshooter - KeyError: 'PKG_MANAGER'

### ISSUE THREAD

**Issue by truekonrads** [microsoft/OMS-Agent-for-Linux#1384]
```
sudo /opt/microsoft/omsagent/bin/troubleshooter
Checking for python install...
Checking all necessary python modules are installed...
Checking all necessary programs are installed...
Running troubleshooting tool in Python 3.8.10...

Welcome to the OMS Agent for Linux Troubleshooter! What is your issue?

================================================================================
1: Agent is unhealthy or heartbeat data missing.
2: Agent doesn't start, can't connect to Log Analytic Services.
3: Syslog issue.
4: Agent consuming high CPU/memory.
5: Installation failures.
6: Custom logs issue.
================================================================================
A: Run through all scenarios.
L: Collect the logs for OMS Agent.
Q: Press 'Q' to quit.
================================================================================
 Please select an option: 3
--------------------------------------------------------------------------------
The troubleshooter can be run in two different modes.
  - Silent Mode runs through with no input required
  - Interactive Mode includes extra checks that require input
 Do you want to run the troubleshooter in silent (s) or interactive (i) mode?: i
Running troubleshooter in interactive mode...
================================================================================
CHECKING FOR SYSLOG ISSUES...
Checking if omsagent installed and running...
Traceback (most recent call last):
  File "/opt/microsoft/omsagent/tst/modules/helpers.py", line 26, in geninfo_lookup
    val = general_info[key]
KeyError: 'PKG_MANAGER'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/microsoft/omsagent/tst/modules/helpers.py", line 65, in get_os_version
    (vm_dist, vm_ver, vm_id) = platform.linux_distribution()
AttributeError: module 'platform' has no attribute 'linux_distribution'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/microsoft/omsagent/tst/modules/main.py", line 254, in <module>
    run_troubleshooter()
  File "/opt/microsoft/omsagent/tst/modules/main.py", line 204, in run_troubleshooter
    success = section(interactive=interactive_mode)
  File "/opt/microsoft/omsagent/tst/modules/syslog_tst/syslog.py", line 22, in check_syslog
    if (get_oms_version() == None):
  File "/opt/microsoft/omsagent/tst/modules/install/check_oms.py", line 15, in get_oms_version
    version = get_package_version('omsagent')
  File "/opt/microsoft/omsagent/tst/modules/install/check_pkgs.py", line 7, in get_package_version
    pkg_mngr = geninfo_lookup('PKG_MANAGER')
  File "/opt/microsoft/omsagent/tst/modules/helpers.py", line 28, in geninfo_lookup
    updated_geninfo = update_geninfo_all()
  File "/opt/microsoft/omsagent/tst/modules/helpers.py", line 244, in update_geninfo_all
    os = get_os_version()
  File "/opt/microsoft/omsagent/tst/modules/helpers.py", line 67, in get_os_version
    (vm_dist, vm_ver, vm_id) = platform.dist()
AttributeError: module 'platform' has no attribute 'dist'
```

OMS agent version omsagent-1.13.40-0.universal.x64.sh downoaded 29/09/2021

**Comment by TrevorBarry** [comment]
Same here, just downloaded the OMS agent today (10/19/2021).

**Comment by echennells** [comment]
Same issue here as well,  Ubuntu 20.04.1 .  Freshly installed version of omsagent.

**Comment by echennells** [comment]
There is a fix coming.  

https://github.com/microsoft/OMS-Agent-for-Linux/pull/1403/commits/01f0686b4abe604c25f1b570e98d1b36bd03b69c

**Comment by 26498** [comment]
Same issue here as well, Ubuntu 20.04.1 . Freshly installed version of omsagent.

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
