### ISSUE TITLE
Use OmsAgentForLinux-1.13.40 in a Linux Azure VM. Log Analytics workspace can't receive VM data

### ISSUE THREAD

**Issue by paulliu10** [microsoft/OMS-Agent-for-Linux#1404]
We use OmsAgentForLinux-1.13.40 in a Linux Azure VM.

On the Azure portal I can see that the VM is connected to the workspace, but I can't get the data, please help to solve this issue, I really appreciate it.

I can see the following error message in the VM from /var/opt/microsoft/omsagent/log/omsagent.log:
====================================================================
2021-11-09 06:41:45 +0000 [error]: Error sending the telemetry request to OMS agent management service: execution expired
2021-11-09 06:41:45 +0000 [error]: Error sending OMS agent management service telemetry request. No HTTP code
2021-11-09 06:42:00 +0000 [info]: Sending OMS Heartbeat succeeded at 2021-11-09T06:42:00.213Z
2021-11-09 06:43:00 +0000 [info]: Sending OMS Heartbeat succeeded at 2021-11-09T06:43:00.214Z
2021-11-09 06:44:00 +0000 [info]: Sending OMS Heartbeat succeeded at 2021-11-09T06:44:00.214Z
2021-11-09 06:44:44 +0000 [warn]: retry succeeded. plugin_id="object:3ffacefc052c"
2021-11-09 06:45:00 +0000 [warn]: retry succeeded. plugin_id="object:3ffacf0f229c"
2021-11-09 06:45:00 +0000 [info]: Sending OMS Heartbeat succeeded at 2021-11-09T06:45:00.215Z
2021-11-09 06:45:14 +0000 [info]: Encountered retryable exception. Will retry sending data later.
2021-11-09 06:45:14 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2021-11-09 06:45:14 +0000 error_class="RuntimeError" error="Net::HTTP.Post raises exception: Net::OpenTimeout, 'execution expired'" plugin_id="object:3ffacefc052c"
  2021-11-09 06:45:14 +0000 [warn]: /opt/microsoft/omsagent/plugin/out_oms.rb:78:in `rescue in handle_record'
  2021-11-09 06:45:14 +0000 [warn]: /opt/microsoft/omsagent/plugin/out_oms.rb:55:in `handle_record'
  2021-11-09 06:45:14 +0000 [warn]: /opt/microsoft/omsagent/plugin/out_oms.rb:123:in `block (2 levels) in self_write'
  2021-11-09 06:45:14 +0000 [warn]: /opt/microsoft/omsagent/plugin/out_oms.rb:122:in `each'
  2021-11-09 06:45:14 +0000 [warn]: /opt/microsoft/omsagent/plugin/out_oms.rb:122:in `block in self_write'
  2021-11-09 06:45:14 +0000 [warn]: /opt/microsoft/omsagent/plugin/out_oms.rb:121:in `each'
  2021-11-09 06:45:14 +0000 [warn]: /opt/microsoft/omsagent/plugin/out_oms.rb:121:in `self_write'
  2021-11-09 06:45:14 +0000 [warn]: /opt/microsoft/omsagent/plugin/out_oms.rb:142:in `write'
  2021-11-09 06:45:14 +0000 [warn]: /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.6.0/gems/fluentd-0.12.40/lib/fluent/buffer.rb:354:in `write_chunk'
  2021-11-09 06:45:14 +0000 [warn]: /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.6.0/gems/fluentd-0.12.40/lib/fluent/buffer.rb:333:in `pop'
  2021-11-09 06:45:14 +0000 [warn]: /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.6.0/gems/fluentd-0.12.40/lib/fluent/output.rb:342:in `try_flush'
  2021-11-09 06:45:14 +0000 [warn]: /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.6.0/gems/fluentd-0.12.40/lib/fluent/output.rb:149:in `run'
2021-11-09 06:45:31 +0000 [info]: Encountered retryable exception. Will retry sending data later.
2021-11-09 06:45:31 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2021-11-09 06:45:29 +0000 error_class="RuntimeError" error="Net::HTTP.Post raises exception: Net::OpenTimeout, 'execution expired'" plugin_id="object:3ffacf0f229c"
  2021-11-09 06:45:31 +0000 [warn]: suppressed same stacktrace
2021-11-09 06:45:44 +0000 [info]: Encountered retryable exception. Will retry sending data later.
2021-11-09 06:45:44 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2021-11-09 06:46:19 +0000 error_class="RuntimeError" error="Net::HTTP.Post raises exception: Net::OpenTimeout, 'execution expired'" plugin_id="object:3ffacefc052c"
  2021-11-09 06:45:44 +0000 [warn]: suppressed same stacktrace
2021-11-09 06:46:00 +0000 [info]: Sending OMS Heartbeat succeeded at 2021-11-09T06:46:00.225Z
2021-11-09 06:46:01 +0000 [info]: Encountered retryable exception. Will retry sending data later.
2021-11-09 06:46:01 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2021-11-09 06:46:27 +0000 error_class="RuntimeError" error="Net::HTTP.Post raises exception: Net::OpenTimeout, 'execution expired'" plugin_id="object:3ffacf0f229c"
  2021-11-09 06:46:01 +0000 [warn]: suppressed same stacktrace
2021-11-09 06:46:32 +0000 [info]: nxOMSAuditdPlugin STATUS: {"Timestamp"=>"2021-11-09T06:46:31.000Z", "Computer"=>"cnaz1plappap03", "RecordType"=>"AUOMS_METRIC", "RecordTypeCode"=>10006, "Namespace"=>"DSC", "Name"=>"Test_Start", "version"=>"1.9", "Message"=>"Start", "Data"=>"{\"has_auditd\":true,\"auditd_pid\":1009,\"auomscollect_pid\":1015,\"auoms_pid\":1059}"}
2021-11-09 06:46:38 +0000 [info]: nxOMSAuditdPlugin STATUS: {"Timestamp"=>"2021-11-09T06:46:32.000Z", "Computer"=>"cnaz1plappap03", "RecordType"=>"AUOMS_METRIC", "RecordTypeCode"=>10006, "Namespace"=>"DSC", "Name"=>"Test_End", "version"=>"1.9", "Message"=>"Set Operation Not Needed", "Data"=>"{\"has_auditd\":true,\"auditd_pid\":1009,\"auomscollect_pid\":1015,\"auoms_pid\":1059}"}
2021-11-09 06:46:47 +0000 [error]: Error sending the telemetry request to OMS agent management service: execution expired
2021-11-09 06:46:47 +0000 [error]: Error sending OMS agent management service telemetry request. No HTTP code
2021-11-09 06:46:49 +0000 [info]: Encountered retryable exception. Will retry sending data later.
2021-11-09 06:46:49 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2021-11-09 06:48:26 +0000 error_class="RuntimeError" error="Net::HTTP.Post raises exception: Net::OpenTimeout, 'execution expired'" plugin_id="object:3ffacefc052c"
  2021-11-09 06:46:49 +0000 [warn]: suppressed same stacktrace
2021-11-09 06:46:57 +0000 [info]: Encountered retryable exception. Will retry sending data later.
2021-11-09 06:46:57 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2021-11-09 06:48:31 +0000 error_class="RuntimeError" error="Net::HTTP.Post raises exception: Net::OpenTimeout, 'execution expired'" plugin_id="object:3ffacf0f229c"
  2021-11-09 06:46:57 +0000 [warn]: suppressed same stacktrace
2021-11-09 06:47:00 +0000 [info]: Sending OMS Heartbeat succeeded at 2021-11-09T06:47:00.226Z
2021-11-09 06:47:33 +0000 [warn]: retry succeeded. plugin_id="object:3ffacf0e397c"
2021-11-09 06:48:00 +0000 [info]: Sending OMS Heartbeat succeeded at 2021-11-09T06:48:00.227Z
2021-11-09 06:48:04 +0000 [info]: Encountered retryable exception. Will retry sending data later.
2021-11-09 06:48:04 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2021-11-09 06:48:06 +0000 error_class="RuntimeError" error="Net::HTTP.Post raises exception: Net::OpenTimeout, 'execution expired'" plugin_id="object:3ffacf0e397c"
  2021-11-09 06:48:04 +0000 [warn]: suppressed same stacktrace
2021-11-09 06:48:36 +0000 [info]: Encountered retryable exception. Will retry sending data later.
2021-11-09 06:48:36 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2021-11-09 06:49:13 +0000 error_class="RuntimeError" error="Net::HTTP.Post raises exception: Net::OpenTimeout, 'execution expired'" plugin_id="object:3ffacf0e397c"
  2021-11-09 06:48:36 +0000 [warn]: suppressed same stacktrace
2021-11-09 06:48:56 +0000 [info]: Encountered retryable exception. Will retry sending data later.
2021-11-09 06:48:56 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2021-11-09 06:52:02 +0000 error_class="RuntimeError" error="Net::HTTP.Post raises exception: Net::OpenTimeout, 'execution expired'" plugin_id="object:3ffacefc052c"
  2021-11-09 06:48:56 +0000 [warn]: suppressed same stacktrace
2021-11-09 06:48:57 +0000 [warn]: retry succeeded. plugin_id="object:3ffacef1724c"
2021-11-09 06:49:00 +0000 [info]: Sending OMS Heartbeat succeeded at 2021-11-09T06:49:00.227Z
2021-11-09 06:49:01 +0000 [info]: Encountered retryable exception. Will retry sending data later.
2021-11-09 06:49:01 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2021-11-09 06:52:05 +0000 error_class="RuntimeError" error="Net::HTTP.Post raises exception: Net::OpenTimeout, 'execution expired'" plugin_id="object:3ffacf0f229c"
  2021-11-09 06:49:01 +0000 [warn]: suppressed same stacktrace
2021-11-09 06:49:28 +0000 [info]: Encountered retryable exception. Will retry sending data later.
2021-11-09 06:49:28 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2021-11-09 06:49:28 +0000 error_class="RuntimeError" error="Net::HTTP.Post raises exception: Net::OpenTimeout, 'execution expired'" plugin_id="object:3ffacef1724c"
  2021-11-09 06:49:28 +0000 [warn]: suppressed same stacktrace
2021-11-09 06:49:43 +0000 [info]: Encountered retryable exception. Will retry sending data later.
2021-11-09 06:49:43 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2021-11-09 06:51:27 +0000 error_class="RuntimeError" error="Net::HTTP.Post raises exception: Net::OpenTimeout, 'execution expired'" plugin_id="object:3ffacf0e397c"
  2021-11-09 06:49:43 +0000 [warn]: suppressed same stacktrace
2021-11-09 06:49:58 +0000 [info]: Encountered retryable exception. Will retry sending data later.
2021-11-09 06:49:58 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2021-11-09 06:50:34 +0000 error_class="RuntimeError" error="Net::HTTP.Post raises exception: Net::OpenTimeout, 'execution expired'" plugin_id="object:3ffacef1724c"
  2021-11-09 06:49:58 +0000 [warn]: suppressed same stacktrace
2021-11-09 06:50:00 +0000 [info]: Sending OMS Heartbeat succeeded at 2021-11-09T06:50:00.228Z
2021-11-09 06:51:00 +0000 [info]: Sending OMS Heartbeat succeeded at 2021-11-09T06:51:00.229Z
2021-11-09 06:51:04 +0000 [info]: Encountered retryable exception. Will retry sending data later.
2021-11-09 06:51:04 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2021-11-09 06:52:27 +0000 error_class="RuntimeError" error="Net::HTTP.Post raises exception: Net::OpenTimeout, 'execution expired'" plugin_id="object:3ffacef1724c"
  2021-11-09 06:51:04 +0000 [warn]: suppressed same stacktrace
2021-11-09 06:51:50 +0000 [error]: Error sending the telemetry request to OMS agent management service: execution expired
2021-11-09 06:51:50 +0000 [error]: Error sending OMS agent management service telemetry request. No HTTP code
2021-11-09 06:51:57 +0000 [info]: Encountered retryable exception. Will retry sending data later.
2021-11-09 06:51:57 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2021-11-09 06:55:08 +0000 error_class="RuntimeError" error="Net::HTTP.Post raises exception: Net::OpenTimeout, 'execution expired'" plugin_id="object:3ffacf0e397c"
  2021-11-09 06:51:57 +0000 [warn]: suppressed same stacktrace
2021-11-09 06:52:00 +0000 [info]: Sending OMS Heartbeat succeeded at 2021-11-09T06:52:00.230Z
====================================================================
[omsagentlog omsconfiglog.zip](https://github.com/microsoft/OMS-Agent-for-Linux/files/7519423/omsagentlog.omsconfiglog.zip)
[omsagentlog omsconfiglog.zip](https://github.com/microsoft/OMS-Agent-for-Linux/files/7519426/omsagentlog.omsconfiglog.zip)

**Comment by paulliu10** [comment]
Hope you are doing well.

Are there any updates on this issue? 

Thank you!

**Comment by paulliu10** [comment]
I wonder if anyone could help with this problem, I would really appreciate it.

Thank you!

**Comment by anthonyAA11** [comment]
Hi, did you solved this issue, if yes how ?

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
