### ISSUE TITLE
OMS Agent Start fail - x86_64-linux/openssl.so (LoadError)

### ISSUE THREAD

**Issue by shaneholloman** [Microsoft/OMS-Agent-for-Linux#173]
**Version** `omsagent-1.1.0-239.universal.x64.sh`

```
root@us:~# service omsagent restart
 * Shutting down Operations Management Suite agent:                                                                                  [ OK ]
 * Starting Operations Management Suite agent:                                                                                              /opt/microsoft/omsagent/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': /opt/microsoft/omsagent/ruby/lib/ruby/2.2.0/x86_64-linux/openssl.so: undefined symbol: SSLv3_method - /opt/microsoft/omsagent/ruby/lib/ruby/2.2.0/x86_64-linux/openssl.so (LoadError)
        from /opt/microsoft/omsagent/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/microsoft/omsagent/ruby/lib/ruby/2.2.0/openssl.rb:17:in `<top (required)>'
        from /opt/microsoft/omsagent/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/microsoft/omsagent/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/microsoft/omsagent/ruby/lib/ruby/2.2.0/net/https.rb:22:in `<top (required)>'
        from /opt/microsoft/omsagent/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/microsoft/omsagent/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/microsoft/omsagent/plugin/oms_common.rb:11:in `<class:Common>'
        from /opt/microsoft/omsagent/plugin/oms_common.rb:8:in `<module:OMS>'
        from /opt/microsoft/omsagent/plugin/oms_common.rb:1:in `<top (required)>'
        from /opt/microsoft/omsagent/plugin/changetracking_lib.rb:6:in `require_relative'
        from /opt/microsoft/omsagent/plugin/changetracking_lib.rb:6:in `<top (required)>'
        from /opt/microsoft/omsagent/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/microsoft/omsagent/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.12.24/lib/fluent/plugin.rb:89:in `block in load_plugin_dir'
        from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.12.24/lib/fluent/plugin.rb:87:in `each'
        from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.12.24/lib/fluent/plugin.rb:87:in `load_plugin_dir'
        from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.12.24/lib/fluent/engine.rb:138:in `load_plugin_dir'
        from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.12.24/lib/fluent/supervisor.rb:513:in `block in init_engine'
        from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.12.24/lib/fluent/supervisor.rb:510:in `each'
        from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.12.24/lib/fluent/supervisor.rb:510:in `init_engine'
        from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.12.24/lib/fluent/supervisor.rb:166:in `block in start'
        from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.12.24/lib/fluent/supervisor.rb:360:in `call'
        from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.12.24/lib/fluent/supervisor.rb:360:in `main_process'
        from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.12.24/lib/fluent/supervisor.rb:164:in `start'
        from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.12.24/lib/fluent/command/fluentd.rb:173:in `<top (required)>'
        from /opt/microsoft/omsagent/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /opt/microsoft/omsagent/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.12.24/bin/fluentd:5:in `<top (required)>'
        from /opt/microsoft/omsagent/bin/omsagent:23:in `load'
        from /opt/microsoft/omsagent/bin/omsagent:23:in `<main>'
                                                                                                                                     [fail]
root@us:~#
```

```
root@us:~# openssl version -a
OpenSSL 1.0.2h  3 May 2016
built on: reproducible build, date unspecified
platform: debian-amd64
options:  bn(64,64) rc4(16x,int) des(idx,cisc,16,int) blowfish(idx)
compiler: gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -m64 -DL_ENDIAN -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wa,--noexecstack -Wall -DMD32_REG_T=int -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
OPENSSLDIR: "/usr/lib/ssl"
root@us:~#
```

```
root@us:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
root@us:~#
```

**Comment by rjcrystal** [comment]
i had the same problem, please refer issue #106

**Comment by NarineM** [comment]
This has been resolved in latest code base that sits in master branch. Azure VM extension also offers the latest omsagent #1.3.12 which has the fix for ruby symbols. Give it a try and let us know if you still see this repro.

**Comment by lagalbra** [comment]
@shaneholloman @rjcrystal Please verify that using the [latest agent release](https://github.com/Microsoft/OMS-Agent-for-Linux/releases/latest) resolves this issue. If this error still occurs, please update this thread; otherwise, this issue will be closed.

**Comment by sbdtu5498** [comment]
Hi Team,

We are still getting this error on our end in the OMS agent v1.14.23

```
# rpm -qi omsagent | grep -i version | awk '{ print $3 }'
warning: Signature not supported. Hash algorithm SHA1 not available.
1.14.23
```

and

```
# systemctl status omsagent-3a793903-2359-4327-a0cc-f1fa6399103f.service 
× omsagent-3a793903-2359-4327-a0cc-f1fa6399103f.service - Operations Management Suite agent
     Loaded: loaded (/usr/lib/systemd/system/omsagent-3a793903-2359-4327-a0cc-f1fa6399103f.service; enabled; preset: disabled)
     Active: failed (Result: exit-code) since Mon 2024-07-29 10:43:47 BST; 2s ago
   Duration: 282ms
    Process: 3089302 ExecStart=/opt/microsoft/omsagent/bin/omsagent -d /var/opt/microsoft/omsagent/3a793903-2359-4327-a0cc-f1fa6399103f/run/omsagent.pid -o /var/opt/microsoft/omsagent/3a793903-2359-4327-a0cc-f1fa6399103f/log/omsagent.log -c /etc/opt/microsoft/omsagent/3a793903-2359-4327-a0cc-f1fa6399103f/conf/omsagent.conf --no-supervisor (code=exited, status=127)
   Main PID: 3089302 (code=exited, status=127)
        CPU: 224ms

Jul 29 10:43:46 hostname systemd[1]: Started Operations Management Suite agent.
Jul 29 10:43:47 hostname omsagent[3089302]: /opt/microsoft/omsagent/ruby/bin/ruby: symbol lookup error: /opt/microsoft/omsagent/ruby/lib/ruby/2.6.0/x86_64-linux/openssl.so: undefined symbol: SSL_library_init
Jul 29 10:43:47 hostname systemd[1]: omsagent-3a793903-2359-4327-a0cc-f1fa6399103f.service: Main process exited, code=exited, status=127/n/a
Jul 29 10:43:47 hostname systemd[1]: omsagent-3a793903-2359-4327-a0cc-f1fa6399103f.service: Failed with result 'exit-code'.
```

Can someone please help?
