### ISSUE TITLE
Problem when installing on ubuntu 16.04

### ISSUE THREAD

**Issue by msternik** [Microsoft/OMS-Agent-for-Linux#370]
Hi,

I have problems installing the agent via the command:

wget https://raw.githubusercontent.com/Microsoft/OMS-Agent-for-Linux/master/installer/scripts/onboard_agent.sh && sh onboard_agent.sh -w ** -s ** -d opinsights.azure.com

The errors are as per below. Any idea how to fix this? Thanks!

/var/lib/dpkg/info/scx.postinst: 154: /var/lib/dpkg/info/scx.postinst: /opt/omi/bin/service_control: not found
dpkg: error processing package scx (--install):
 subprocess installed post-installation script returned error exit status 127
dpkg: dependency problems prevent configuration of omsagent:
 omsagent depends on scx (>= 1.6.2.129); however:
  Package scx is not configured yet.
  Version of scx on system, provided by scx:amd64, is <none>.

dpkg: error processing package omsagent (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of omsconfig:
 omsconfig depends on omsagent (>= 1.0.0); however:
  Package omsagent is not configured yet.
  Version of omsagent on system, provided by omsagent:amd64, is <none>.

dpkg: error processing package omsconfig (--install):
 dependency problems - leaving unconfigured
Processing triggers for systemd (229-4ubuntu13) ...
Processing triggers for ureadahead (0.100.0-19) ...
Errors were encountered while processing:
 scx
 omsagent
 omsconfig

**Comment by lagalbra** [comment]
@msternik What Linux distribution/version did this run on?

My first suggestion is to purge and reinstall the agent shell bundle that was downloaded by the `onboard_agent.sh` script (replace `x64` with `x86` if yours is a 32-bit machine):
> `sudo sh omsagent-1.2.0-148.universal.x64.sh --purge`
> `sudo sh omsagent-1.2.0-148.universal.x64.sh --upgrade -w ** -s ** -d opinsights.azure.com`

**Comment by msternik** [comment]
Hi @lagalbra , thanks for your response and apologies for delay in replying. I managed to successfully install the agent a couple of weeks ago (after days of trying with different versions, as the documentation is not clear on what version we should be using. I have just checked the onboarding script and i think it was updated, however in the docs the download link points to the 1.2 version.

Anyways, 2 days ago my agents stopped working on all machines. I  have noticed there were some updates to the agent at that time. Below are some of the error logs attached. 


  2017-03-11 10:56:30 +0000 [error]: suppressed same stacktrace
error   Missing configuration file: /etc/opt/microsoft/omsagent/**/conf/omsadmin.conf
2017-03-11 10:58:30 +0000 [error]: Missing configuration file: /etc/opt/microsoft/omsagent/**/conf/omsadmin.conf
error   Error loading configuration from /etc/opt/microsoft/omsagent/**/conf/omsadmin.conf
2017-03-11 10:58:30 +0000 [error]: Error loading configuration from /etc/opt/microsoft/omsagent/**/conf/omsadmin.conf
2017-03-11 11:01:30 +0000 [warn]: emit transaction failed: error_class=Errno::ENOENT error="No such file or directory @ rb_sysopen - /var/opt/microsoft/omsagent/**/state/out_oms_health.b54a7266813c6356e.buffer" tag="oms.health"
  2017-03-11 11:01:30 +0000 [warn]: suppressed same stacktrace
2017-03-11 11:01:30 +0000 [error]: No such file or directory @ rb_sysopen - /var/opt/microsoft/omsagent/**/state/out_oms_health.b54a7266813c6356e.buffer
  2017-03-11 11:01:30 +0000 [error]: suppressed same stacktrace

**Comment by msternik** [comment]
By the way, is this code maintained by Microsoft so that I can ask the support team for help?

**Comment by lagalbra** [comment]
As for which version you should be using, we recommend the latest released version, which is the first one given on our [GitHub Releases page](https://github.com/Microsoft/OMS-Agent-for-Linux/releases) (currently 1.3.1-15). I've submitted a pull request to correct the oversight on the main [README.md](https://github.com/Microsoft/OMS-Agent-for-Linux/blob/master/README.md) page.

Can you provide the logs that indicated an update to the agent? What is the version of the agent that you currently have installed?

Yes, this code is maintained by my team at Microsoft, and this GitHub Issues page is one path for support.

**Comment by msternik** [comment]
Hi @lagalbra ,

Thanks for your reply. I have managed to fix my issue - will monitor the agents and see if they are working fine. 

There were some problems with permissions both to the omsagent foler in /var/opt/microsoft/omsagent and custom logs.

As for omsagent folder I just changed the permisions from root to omsagent and worked fine.

For custom logs, I used: 
ls -l <file-path-for-logs>
usermod -aG <file-group> omsagent 

There is one thing that worries my though - one of my agents logged errors as per below. Do you know what could be causing this and how to fix it?

Thanks a lot!

2017-03-13 19:29:10 +0000 [error]: HTTP Error: (request-id=; class=Net::HTTPBadRequest; code=400; message=The specified block list is invalid.; body=<feff><?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidBlockList</Code><Message>The specified block list is invalid.
RequestId:caacc851-0001-0124-7330-9cb48e000000
Time:2017-03-13T19:29:10.6992221Z</Message></Error>;)
2017-03-13 19:29:10 +0000 [info]: Encountered retryable exception. Will retry sending data later.
2017-03-13 19:29:10 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2017-03-13 19:29:39 +0000 error_class="RuntimeError" error="HTTP error: (request-id=; class=Net::HTTPBadRequest; code=400; message=The specified block list is invalid.; body=\xEF\xBB\xBF<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>InvalidBlockList</Code><Message>The specified block list is invalid.\nRequestId:caacc851-0001-0124-7330-9cb48e000000\nTime:2017-03-13T19:29:10.6992221Z</Message></Error>;)" plugin_id="object:2ac4babf03d4"
  2017-03-13 19:29:10 +0000 [warn]: suppressed same stacktrace
2017-03-13 19:29:41 +0000 [warn]: retry succeeded. plugin_id="object:2ac4babf03d

**Comment by lagalbra** [comment]
If you have custom logs configured to monitor a particular file which does not grant permissions to the omsagent user, then changing the permissions (like you did) is the temporary solution. We are currently working on a solution so you do not have to change the permissions yourself.

As for the HTTP error you provided, it looks like a temporary issue, since the last line indicates that the data was sent successfully during a retry.

**Comment by lagalbra** [comment]
Let me know if you have any more questions; otherwise I will close this GitHub issue thread.

**Comment by msternik** [comment]
Thanks @lagalbra. These errors occur every now and then - roughly every 20 mins (sometimes restarting the agent). I can see the data is sent to the dashboard, however it would be good to know why this happens.

**Comment by lagalbra** [comment]
To debug this further, I would need more logs. Could you change the log_level to debug and then restart the agent and include the error and surrounding lines in a message?

1. Open `/etc/opt/microsoft/omsagent/conf/omsagent.conf` with sudo and change any `log_level` lines to `log_level trace`
2. Run `sudo /opt/microsoft/omsagent/bin/service_control restart`

**Comment by lagalbra** [comment]
@msternik We've recently released a patch for the OMSAgent. Please verify that using the [latest agent release](https://github.com/Microsoft/OMS-Agent-for-Linux/releases/latest) resolves this issue. If this error still occurs, please update this thread with the requested logs and details; otherwise, this issue will be closed.

**Comment by msternik** [comment]
Hi, with the latest release all my agents apart from one stopped working. when i try to restart them I get an error as per below.  This is very frustrating.

2017-04-10 11:26:24 +0000 [info]: reading config file path="/etc/opt/microsoft/omsagent/conf/omsagent.conf"
/opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/supervisor.rb:468:in `read': No such file or directory @ rb_sysopen - /etc/opt/microsoft/omsagent/conf/omsagent.conf (Errno::ENOENT)
        from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/supervisor.rb:468:in `read_config'
        from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/supervisor.rb:138:in `start'
        from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/command/fluentd.rb:173:in `<top (required)>'
        from /opt/microsoft/omsagent/ruby/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /opt/microsoft/omsagent/ruby/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/bin/fluentd:5:in `<top (required)>'
        from /opt/microsoft/omsagent/bin/omsagent-0bc135bf-e9b5-4595-a5af-98432ccd2574:22:in `load'
        from /opt/microsoft/omsagent/bin/omsagent-0bc135bf-e9b5-4595-a5af-98432ccd2574:22:in `<main>'

**Comment by lagalbra** [comment]
@msternik Can you check that `omsagent.conf` exists at this location: `/etc/opt/microsoft/omsagent/conf/omsagent.conf ?`

This file should exist if onboarding succeeded. To verify this, run `sudo sh /opt/microsoft/omsagent/bin/omsadmin.sh -w <workspace ID> -s <primary/shared key>` and make sure the line `Onboarding success` is included in the output.

**Comment by msternik** [comment]
@lagalbra there was never a config folder (I was actually wondering why because the documentation states it should be there). 
This is the output of the command:
```
info	Generating certificate ...
-e info	Onboarding success
Configuring rsyslog for OMS logging
Restarting service: rsyslog
Configuring OMS agent service ...
-e info	Configured omsconfig
-e info	Disable workspace: ***
Unconfiguring OMS agent (systemd) service ...
-e info	Cleanup the folders
Unconfiguring rsyslog for OMS logging
Restarting service: rsyslog
```

**Comment by lagalbra** [comment]
That's odd; it looks like it's configuring your workspace, then immediately removing it. You're not running that omsadmin.sh command with -x or -X, are you?

Can you try a couple things:

1. Check if an omsagent service is running:
`sudo service omsagent-<workspace ID> status`

```
REMOVE=0
sudo sh /opt/microsoft/omsagent/bin/omsadmin.sh -w <workspace ID> -s <primary/shared key>
```

Paste the command into the thread as well, though you can replace your workspace ID and key with ****.

If this doesn't work, purge and then reinstall the agent using the "To install and onboard directly" step from the [instructions](https://github.com/Microsoft/OMS-Agent-for-Linux/blob/master/docs/OMS-Agent-for-Linux.md#steps-to-install-the-oms-agent-for-linux).

**Comment by msternik** [comment]
Hi @lagalbra, it turned out thats I run it with the option -x instead of -w. 
If I run it with option -w, the agent is being installed successfully, however I still don't have any log or config folders. I have checked the command
 `sudo service omsagent-<workspace ID> status` and it was active even if I previously run .`/service-control stop`. 
Perhaps I have a mix of different version of omsagents on my machines?

The only thing that made it work was to stop the omsagent service and run as sudo:
`nohup /opt/microsoft/omsagent/bin/omsagent-0bc135bf-e9b5-4595-a5af-98432ccd2574 >> /opt/microsoft/omsagent/bin/agent.log 2>&1&
`
Now it seems to work fine, but I guess its a bit hacky and will probably go down anyway. Have you guys tested it on Ubuntu 16.04? As I said, none of my machines have log or config folders so maybe the installation fails at some point.

**Comment by msternik** [comment]
Also, as I am checking on other machines, it seems that other workspaces that were installed before the update, were somehow removed or are not picked up by the agent.

**Comment by lagalbra** [comment]
Please purge and reinstall the agent on any machines that you once had configured with -x; this is the strongest way to make sure that they get installed successfully.

Yes, Ubuntu 16.04 is one of the Linux distros that we support and test on.

Can you provide the exact sequence of commands that were executed for the issue you mention where some workspaces were dropped during upgrade, as well as what workspaces were configured before and after those commands?

**Comment by lagalbra** [comment]
@msternik Do you have any update on this issue? Please keep in mind that multi-homing is not fully released yet, so data is not guaranteed to send successfully to more than one workspace configured on the machine.

**Comment by lagalbra** [comment]
Closing due to inactivity
