### ISSUE TITLE
ruby errors during install

### ISSUE THREAD

**Issue by dhermans** [Microsoft/OMS-Agent-for-Linux#393]
trying both omsagent-1.2.0-148.universal.x64.sh and omsagent-1.3.1-15.universal.x64.sh I get this during install on Centos 7 ( recently patched to CentOS Linux release 7.3.1611 (Core) ):

info    Reading onboarding params from: /etc/omsagent-onboard.conf
Ignoring executable-hooks-1.3.2 because its extensions are not built.  Try: gem pristine executable-hooks --version 1.3.2
Ignoring gem-wrappers-1.2.7 because its extensions are not built.  Try: gem pristine gem-wrappers --version 1.2.7
/opt/microsoft/omsagent/ruby/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- gyoku (LoadError)
        from /opt/microsoft/omsagent/ruby/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /opt/microsoft/omsagent/plugin/agent_maintenance_script.rb:10:in `<class:Maintenance>'
        from /opt/microsoft/omsagent/plugin/agent_maintenance_script.rb:5:in `<module:MaintenanceModule>'
        from /opt/microsoft/omsagent/plugin/agent_maintenance_script.rb:3:in `<main>'
error   Error generating certs
System appears to have SELinux installed, attempting to install selinux policy module for logrotate
  Trying /usr/share/selinux/packages/omsagent-logrotate/omsagent-logrotate.pp ...
Warning: Specified workspace xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxdoesn't exist

Also the work specified DOES exist  - last line says it does not

**Comment by lagalbra** [comment]
@dhermans First things first: are you installing the 1.2.0-148 and 1.3.1-15 bundles from our [releases page](https://github.com/Microsoft/OMS-Agent-for-Linux/releases), or are these bundles you built on your own build machine? The reason I ask is because gems like gyoku can get bundled incorrectly if the build machine is not set up properly.

Can you run these commands and provide me with the output:
Purge the bundle from the machine: `sudo sh omsagent-1.3.1-15.universal.x64.sh --purge`
Re-install the bundle, but do not onboard to a workspace: `sudo sh omsagent-1.3.1-15.universal.x64.sh --upgrade`
Check for the gem files: `ls /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/`
Retry [onboarding](https://github.com/Microsoft/OMS-Agent-for-Linux/blob/OMSAgent-201702-v1.3.1-15/docs/OMS-Agent-for-Linux.md#onboarding-using-the-command-line): `sudo sh /opt/microsoft/omsagent/bin/omsadmin.sh -w <WorkspaceID> -s <Shared Key>`

The "Warning: Specified workspace xxx doesn't exist" error occurs because onboarding failed. We will work on improving the error message.

**Comment by dhermans** [comment]
Hi,
Thanks for responding.

Yes I am pulling the release straight from your site - I am not building from source. Following your steps the gems dir has:
 ls /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/
builder-3.2.2   fluentd-0.12.24       multi_json-1.12.1     power_assert-0.3.0  sigdump-0.2.4         test-unit-rr-1.0.5  tzinfo-data-1.2016.4
bundler-1.10.6  gyoku-1.3.1           oj-2.15.0             rake-10.4.2         simplecov-0.6.4       thread_safe-0.3.5   yajl-ruby-1.2.1
cool.io-1.4.4   http_parser.rb-0.6.0  parallel-1.8.0        rdoc-4.2.1          simplecov-html-0.5.3  timecop-0.8.1
flexmock-1.3.3  msgpack-0.5.12        parallel_tests-2.5.0  rr-1.1.2            test-unit-3.1.9       tzinfo-1.2.2


Also can I add that I need to use a proxy - there doesn't seem to be a proxy option on /opt/microsoft/omsagent/bin/omsadmin.sh

How can I specify a proxy?

On the topic of proxy - on a different clean box OMS seems to install cleanly but does not register with OMS. Netstat shows this as well:

tcp        0      1 10.38.128.37:42624      13.70.155.6:443         SYN_SENT    10287/ruby


Thanks!

**Comment by dhermans** [comment]
ok i see there is a separate proxy option on omsadmin.sh so I used that..seems ok:

info    Generating certificate ...
info    Using proxy settings from '/etc/opt/microsoft/omsagent/proxy.conf'
info    Onboarding success


but I can't see anyhing in OMS and get errors: ( still seems to be trying to go direct?? )
2017-03-17 11:35:40 +1100 [info]: Encountered retryable exception. Will retry sending data later.
2017-03-17 11:35:40 +1100 [warn]: temporarily failed to flush the buffer. next_retry=2017-03-17 11:35:41 +1100 error_class="RuntimeError" error="Net::HTTP.Post raises exception: Net::OpenTimeout, 'execution expired'" plugin_id="object:3f8bc017f9cc"
  2017-03-17 11:35:40 +1100 [warn]: /opt/microsoft/omsagent/plugin/out_oms.rb:62:in `rescue in handle_record'
  2017-03-17 11:35:40 +1100 [warn]: /opt/microsoft/omsagent/plugin/out_oms.rb:43:in `handle_record'

**Comment by lagalbra** [comment]
We have [instructions](https://github.com/Microsoft/OMS-Agent-for-Linux/blob/master/docs/OMS-Agent-for-Linux.md#configuring-the-agent-for-use-with-an-http-proxy-server) for onboarding with a proxy. Please follow these rather than just using omsadmin.sh.

**Comment by lagalbra** [comment]
Are you still seeing errors during onboarding on your original Centos 7 machine? It seems to me that all the gem files are present and you are onboarding successfully now.

Please follow these instructions:
1. Purge the agent from the machine: `sudo sh omsagent-1.3.1-15.universal.x64.sh --purge`
2. Install the latest agent (1.3.1-15) according to the [proxy instructions](https://github.com/Microsoft/OMS-Agent-for-Linux/blob/master/docs/OMS-Agent-for-Linux.md#configuring-the-agent-for-use-with-an-http-proxy-server)

Once you have done this, check that you see data in the OMS portal and there are no errors in `/var/opt/microsoft/omsagent/log/omsagent.log`

**Comment by dhermans** [comment]
Hi,
I have a few machines - Centos7, Rhel7 using proxy ( yes am across how to use proxy ) and one not using proxy ( also Centos7 ).

The one without proxy ( with a public IP ) works fine. The proxy based ones never appear in OMS console

Pretty sure this used to work fine with 1.2x client - I had multiple clients registered for ages - is it still available for download somewhere? I will downgrade and try it...

**Comment by lagalbra** [comment]
@KrisBash or @NarineM Could you lend your expertise on the proxy scenario?

1.2.0-148 OMSAgent is available for download [here](https://github.com/Microsoft/OMS-Agent-for-Linux/releases/tag/OMSAgent-201610-v1.2.0-148). You will have to purge any existing agent and the install it, since directly downgrading is not supported.

**Comment by dhermans** [comment]
hi team,
downgrading to 
omsagent-1.2.0-148.universal.x64.sh

and registering via a proxy works perfectly..am happy to help with any diagnosing of 1.3

**Comment by dhermans** [comment]
@lagalbra any news?

**Comment by lagalbra** [comment]
I do not believe this is an issue with the OMSAgent; we have not heard from any other customers about it. Can you please troubleshoot your machine that previous saw errors with 1.3 and proxy by running these commands and providing the output?

1. sudo sh omsagent-1.3.1-15.universal.x64.sh --upgrade -p <proxy> -w <workspace id> -s <shared key>; echo $?

2. tail /var/opt/microsoft/omsagent/log/omsagent.log

3. tail /var/opt/microsoft/omsconfig/omsconfig.log #this may provide no output if the agent was installed in the last five minutes

**Comment by NarineM** [comment]
@dhermans ,

Since it works for you when use the old version 148, but does not work when you use the newest version of omsagent 1.3.1.15, it is most likely because of proxy file location.
The new versions of agent (1.3.0.12 and 1.3.1.15)  use a different proxy file path. In the past it was under etc/opt/microsoft/omsagent/conf/proxy.conf, , now it is under : etc/opt/microsoft/omsagent/proxy.conf.

If you pass proxy settings directly to cmdline using -p http://<proxy user>:<proxy password>@<proxy address>:<proxy port> that should work regardless what version of agent you use (newer or older).

**Comment by lagalbra** [comment]
A workaround that you can try has been documented in this PR https://github.com/Microsoft/OMS-Agent-for-Linux/pull/432

**Comment by lagalbra** [comment]
Closing issue due to inactivity

**Comment by abenbachir** [comment]
I discovered that if you have installed another Ruby from the RVM (Ruby version manager). For visibility purpose I'm updating this case.
 
RVM will cause conflicts with the Ruby shipped by OMSAgent because of the global variable that were set by RVM: GEM_HOME, GEM_PATH.

Here is the how to detect it:

$> ruby --version
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]

$> echo $PATH
/usr/local/rvm/gems/ruby-2.2.2/bin:/usr/local/rvm/gems/ruby-2.2.2@global/bin:/usr/local/rvm/rubies/ruby-2.2.2/bin:/home/banban/jdk1.8.0_144/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/rvm/bin:/root/bin

$> /opt/microsoft/omsagent/ruby/bin/gem environmen
RubyGems Environment:
  - RUBYGEMS VERSION: 3.0.3
  - RUBY VERSION: 2.6.3 (2019-04-16 patchlevel 62) [x86_64-linux]
  - INSTALLATION DIRECTORY: /usr/local/rvm/gems/ruby-2.2.2
  - USER INSTALLATION DIRECTORY: /root/.gem/ruby/2.6.0
  - RUBY EXECUTABLE: /opt/microsoft/omsagent/ruby/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /usr/local/rvm/gems/ruby-2.2.2/bin
  - SPEC CACHE DIRECTORY: /root/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /opt/microsoft/omsagent/ruby/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /usr/local/rvm/gems/ruby-2.2.2
     - /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/rvm/gems/ruby-2.2.2/bin
     - /usr/local/rvm/gems/ruby-2.2.2@global/bin
     - /usr/local/rvm/rubies/ruby-2.2.2/bin
     - /home/banban/jdk1.8.0_144/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /sbin
     - /bin
     - /usr/sbin
     - /usr/bin
     - /usr/local/rvm/bin
     - /root/bin

$> echo $GEM_HOME
/usr/local/rvm/gems/ruby-2.2.2

$> echo $GEM_PATH
/usr/local/rvm/gems/ruby-2.2.2:/usr/local/rvm/gems/ruby-2.2.2@global

here is how to solve it:

#1 An immediate test would be to remove RVM from the PATH environment and re-login again:
     $> mv /etc/profile.d/rvm.sh /etc/profile.d/rvm.sh.bak

#2 For a long-term solution customer should remove RVM from the VM.

3# After removing RVM, you can test quickly using this CMD:
     $> /opt/microsoft/omsagent/ruby/bin/ruby -e "require 'gyoku'; puts 'Test done'"
     Test done
