### ISSUE TITLE
Deployment resulted in error, "malformed status file"

### ISSUE THREAD

**Issue by aw230012** [Microsoft/OMS-Agent-for-Linux#565]
We are trying to install the Microsoft.EnterpriseCloud.Monitoring OmsAgentForLinux onto a Standard_DS13_v2 RedHat 7.2 image and we received the error "malformed status file."

I could not find any information in the troubleshooting guide for this error.  Does anyone know how we can fix this?

Thanks!

**Comment by lagalbra** [comment]
The troubleshooting guide for the OmsAgentForLinux extension is here: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/extensions-oms

In this case, you can see an exact error message by looking at the extension installation output in the file `/var/log/azure/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux/1.4.45.2/extension.log` This output should include an error code that you can reference in the table in the above documentation link.

My first guess is that the parameters you used for workspaceId and workspaceKey did not resolve to their expected values. I would recommend constructing a dictionary like the above in Azure Powershell and seeing if those values can be read or not.

**Comment by NarineM** [comment]
Are you still seeing this or it is been resolved for your deployment?

**Comment by akramwaseem** [comment]
@NarineM @lagalbra ---- Below is the extension.log error message I see.

2018/06/18 19:27:53 ERROR:Enable failed with error: 'ascii' codec can't encode characters in position 67-68: ordinal not in range(128)
2018/06/18 19:27:53 ERROR:Stacktrace: Traceback (most recent call last):
2018/06/18 19:27:53 ERROR:  File "/var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.6.42.0/omsagent.py", line 153, in main
2018/06/18 19:27:53 ERROR:    exit_code = operations[operation]()
2018/06/18 19:27:53 ERROR:  File "/var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.6.42.0/omsagent.py", line 310, in enable
2018/06/18 19:27:53 ERROR:    check_workspace_id_and_key(workspaceId, workspaceKey)
2018/06/18 19:27:53 ERROR:  File "/var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.6.42.0/omsagent.py", line 576, in check_workspace_id_and_key
2018/06/18 19:27:53 ERROR:    encoded_key = base64.b64encode(base64.b64decode(workspace_key))
2018/06/18 19:27:53 ERROR:  File "/usr/lib/python2.7/base64.py", line 73, in b64decode
2018/06/18 19:27:53 ERROR:    return binascii.a2b_base64(s)
2018/06/18 19:27:53 ERROR:UnicodeEncodeError: 'ascii' codec can't encode characters in position 67-68: ordinal not in range(128)
2018/06/18 19:27:53 ERROR:
2018/06/18 19:27:53 ERROR:[Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.6.42.0] Enable failed with error: 'ascii' codec can't encode characters in position 67-68: ordinal not in range(128)
2018/06/18 19:27:53 ERROR:Stacktrace: Traceback (most recent call last):
2018/06/18 19:27:53 ERROR:  File "/var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.6.42.0/omsagent.py", line 153, in main
2018/06/18 19:27:53 ERROR:    exit_code = operations[operation]()
2018/06/18 19:27:53 ERROR:  File "/var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.6.42.0/omsagent.py", line 310, in enable
2018/06/18 19:27:53 ERROR:    check_workspace_id_and_key(workspaceId, workspaceKey)
2018/06/18 19:27:53 ERROR:  File "/var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.6.42.0/omsagent.py", line 576, in check_workspace_id_and_key
2018/06/18 19:27:53 ERROR:    encoded_key = base64.b64encode(base64.b64decode(workspace_key))
2018/06/18 19:27:53 ERROR:  File "/usr/lib/python2.7/base64.py", line 73, in b64decode
2018/06/18 19:27:53 ERROR:    return binascii.a2b_base64(s)
2018/06/18 19:27:53 ERROR:UnicodeEncodeError: 'ascii' codec can't encode characters in position 67-68: ordinal not in range(128)
2018/06/18 19:27:53 ERROR:
2018/06/18 19:27:53 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.6.42.0] Enable,failed,1,Enable failed with error: 'ascii' codec can't encode characters in position 67-68: ordinal not in range(128)
2018/06/18 19:27:53 Stacktrace: Traceback (most recent call last):
2018/06/18 19:27:53   File "/var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.6.42.0/omsagent.py", line 153, in main
2018/06/18 19:27:53     exit_code = operations[operation]()
2018/06/18 19:27:53   File "/var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.6.42.0/omsagent.py", line 310, in enable
2018/06/18 19:27:53     check_workspace_id_and_key(workspaceId, workspaceKey)
2018/06/18 19:27:53   File "/var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.6.42.0/omsagent.py", line 576, in check_workspace_id_and_key
2018/06/18 19:27:53     encoded_key = base64.b64encode(base64.b64decode(workspace_key))
2018/06/18 19:27:53   File "/usr/lib/python2.7/base64.py", line 73, in b64decode
2018/06/18 19:27:53     return binascii.a2b_base64(s)
2018/06/18 19:27:53 UnicodeEncodeError: 'ascii' codec can't encode characters in position 67-68: ordinal not in range(128)
2018/06/18 19:27:53

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
