### ISSUE TITLE
 OMS Agent not resuming to proper working state

### ISSUE THREAD

**Issue by sasarava** [microsoft/OMS-Agent-for-Linux#699]
I started the OMS Agent in a linux VM and it was emitting the data packets as expected. I manually consumed all inodes in that VM by creating new files. Once all the indoes are consumed, the OMS agent keeps running; but, stops emitting the packets. When the inodes are freed after some time, the OMS Agent keeps running in the same state and does not get back to the proper working state in which it emits. It requires a restart to make it emit packets.

Steps to reproduce:
1.	Start the OMS Agent in a Linux VM. [Agent starts emitting packets]
2.	Start creating new files until there are no free inodes. [Now the OMS Agent stops emitting]
3.	Free the indoes by deleting the files created in step 2. [Now the OMS Agent is expected to emit packets. But, it does not]
4.	Restart the OMS Agent [OMS Agent starts working as in Step 1]

Pasting relevant logs:

2018-04-25 06:34:12 +0000 [warn]: emit transaction failed: error_class=Errno::ENOSPC error="No space left on device @ rb_sysopen - /var/opt/microsoft/omsagent/b7a4ab60-6abe-4b0d-ab33-1527263324d5/state/out_oms_health.b56aa67584a473d7c.buffer" tag="oms.health"
  2018-04-25 06:34:12 +0000 [warn]: /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/plugin/buf_file.rb:30:in `initialize'
  2018-04-25 06:34:12 +0000 [warn]: /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/plugin/buf_file.rb:30:in `open'
  2018-04-25 06:34:12 +0000 [warn]: /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/plugin/buf_file.rb:30:in `initialize'
  2018-04-25 06:34:12 +0000 [warn]: /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/plugin/buf_file.rb:134:in `new'
  2018-04-25 06:34:12 +0000 [warn]: /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/plugin/buf_file.rb:134:in `new_chunk'
  2018-04-25 06:34:12 +0000 [warn]: /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/buffer.rb:196:in `block in emit'
  2018-04-25 06:34:12 +0000 [warn]: /opt/microsoft/omsagent/ruby/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
  2018-04-25 06:34:12 +0000 [warn]: /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/buffer.rb:193:in `emit'
  2018-04-25 06:34:12 +0000 [warn]: /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/output.rb:268:in `emit'
  2018-04-25 06:34:12 +0000 [warn]: /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/event_router.rb:154:in `emit'
  2018-04-25 06:34:12 +0000 [warn]: /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/event_router.rb:90:in `emit_stream'
  2018-04-25 06:34:12 +0000 [warn]: /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/plugin/in_monitor_agent.rb:264:in `block in start'
  2018-04-25 06:34:12 +0000 [warn]: /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/plugin/in_monitor_agent.rb:230:in `on_timer'
  2018-04-25 06:34:12 +0000 [warn]: /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/cool.io-1.4.4/lib/cool.io/loop.rb:88:in `run_once'
  2018-04-25 06:34:12 +0000 [warn]: /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/cool.io-1.4.4/lib/cool.io/loop.rb:88:in `run'
  2018-04-25 06:34:12 +0000 [warn]: /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/plugin/in_monitor_agent.rb:272:in `run'
2018-04-25 06:34:12 +0000 [error]: No space left on device @ rb_sysopen - /var/opt/microsoft/omsagent/b7a4ab60-6abe-4b0d-ab33-1527263324d5/state/out_oms_health.b56aa67584a473d7c.buffer
  2018-04-25 06:34:12 +0000 [error]: suppressed same stacktrace
2018-04-25 06:35:31 +0000 [info]: DSC AgentService Heartbeat success
2018-04-25 06:39:11 +0000 [warn]: emit transaction failed: error_class=Errno::ENOSPC error="No space left on device @ rb_sysopen - /var/opt/microsoft/omsagent/b7a4ab60-6abe-4b0d-ab33-1527263324d5/state/out_oms_health.b56aa6875ea69973a.buffer" tag="oms.health"
  2018-04-25 06:39:11 +0000 [warn]: suppressed same stacktrace
2018-04-25 06:39:11 +0000 [error]: No space left on device @ rb_sysopen - /var/opt/microsoft/omsagent/b7a4ab60-6abe-4b0d-ab33-1527263324d5/state/out_oms_health.b56aa6875ea69973a.buffer
  2018-04-25 06:39:11 +0000 [error]: suppressed same stacktrace

**Comment by NarineM** [comment]
Based on this log, the agent is still trying to send data from the currently in progress buffer.Since your machine does not have any free space , it fails . When you restart the service the buffer will be reset thus you would not see these errors.

**Comment by sasarava** [comment]
If the inodes in the machine are freed up, the agent should be able to send the data without a restart. Even if the inodes is freed up, the OMS agent runs but does not send the data.

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
