### ISSUE TITLE
Multiline is not parsed properly

### ISSUE THREAD

**Issue by evilr00t** [Microsoft/OMS-Agent-for-Linux#752]
Hello!

I'm working on parsing java logs to OMS.
Unfortunately, there's something weird with OMS.

OMS does not parse logs properly.

my OMS config
```
<source>
    type sudo_tail
    format multiline
    format_firstline /\d{4}-\d{1,2}-\d{1,2}/
    format1 /^(?<time>\d{4}-\d{1,2}-\d{1,2}T\d{1,2}:\d{1,2}:\d{1,2}.\w+) \[(?<loglevel>.*?)\] \[(?<logger>.*?)\] (?<message>.*)/
    format2 /^(?<exception>.*): (?<exception_msg>.*): (?<error_code>\d{1,3})/
    format3 /(?<stacktrace>.*)/
    #time_format %Y-%m-%dT%H:%M:%S
    tag oms.api.idamevents.*
    path /var/log/XXX/XXX.log
    pos_file /var/opt/microsoft/omsagent/state/XXX.pos
    read_from_head true
    run_interval 60
</source>
```

OMS says:

```
2018-07-19 13:20:48 +0000 [warn]: pattern doesn't match: "2018-07-19T13:20:47.598Z [ERROR] [XXX.service.mq.consumer.implementation.ApacheMqConsumer] Error while trying to process the message "
2018-07-19 13:20:48 +0000 [warn]: pattern doesn't match: "XXX.core.exception.IdamException: Response was an Error of: 503"
2018-07-19 13:20:48 +0000 [warn]: pattern doesn't match: "\tat XXX.service.mq.consumer.implementation.ApacheMqConsumer.sendMqMessage(ApacheMqConsumer.java:63)"
2018-07-19 13:20:48 +0000 [warn]: pattern doesn't match: "\tat XXX.service.mq.consumer.implementation.ApacheMqConsumer.consume(ApacheMqConsumer.java:43)"
2018-07-19 13:20:48 +0000 [warn]: pattern doesn't match: "\tat XXX.service.mq.consumer.core.ActiveMqConsumerHandler.processMessage(ActiveMqConsumerHandler.java:101)"
2018-07-19 13:20:48 +0000 [warn]: pattern doesn't match: "\tat XXX.service.mq.consumer.core.ActiveMqConsumerHandler.runReceiveLoop(ActiveMqConsumerHandler.java:240)"
2018-07-19 13:20:48 +0000 [warn]: pattern doesn't match: "\tat XXX.service.mq.consumer.core.ActiveMqConsumerHandler.startReceiving(ActiveMqConsumerHandler.java:206)"
2018-07-19 13:20:48 +0000 [warn]: pattern doesn't match: "\tat XXX.service.mq.consumer.core.ActiveMqConsumerHandler.prepareConsumerAndStartReceiving(ActiveMqConsumerHandler.java:195)"
2018-07-19 13:20:48 +0000 [warn]: pattern doesn't match: "\tat XXX.service.mq.consumer.core.ActiveMqConsumerHandler.startConnectionRunReceiver(ActiveMqConsumerHandler.java:180)"
2018-07-19 13:20:48 +0000 [warn]: pattern doesn't match: "\tat XXX.service.mq.consumer.core.ActiveMqConsumerHandler.run(ActiveMqConsumerHandler.java:137)"
2018-07-19 13:20:48 +0000 [warn]: pattern doesn't match: "\tat java.lang.Thread.run(Thread.java:748)"
```

where fluentd 0.12.40 (same as in latest OMS) works fine and I can see the parsed log.

fluentd config

```
<source>
    type tail
    format multiline
    format_firstline /\d{4}-\d{1,2}-\d{1,2}/
    format1 /^(?<time>\d{4}-\d{1,2}-\d{1,2}T\d{1,2}:\d{1,2}:\d{1,2}.\d{3}Z) \[(?<loglevel>.*?)\] \[(?<logger>.*?)\] (?<message>.*)/
    format2 /^(?<exception>.*): (?<exception_msg>.*): (?<error_code>\d{1,3})/
    format3 /(?<stacktrace>.*)/
    time_format %Y-%m-%dT%H:%M:%L
    tag oms.api.idamevents.*
    path /tmp/XXX.log
    read_from_head true
    run_interval 60
</source>
```

and fluentd produces:

```
2018-07-19 12:07:00 +0000 oms.api.XXX.tmp.XXX.log: {"loglevel":"ERROR","logger":"XXX.service.mq.consumer.implementation.ApacheMqConsumer","message":"Error while trying to process the message\n","exception":"XXX.core.exception.IdamException","exception_msg":"Response was an Error of","error_code":"503","stacktrace":"\n  at XXX.service.mq.consumer.implementation.ApacheMqConsumer.sendMqMessage(ApacheMqConsumer.java:63)\n  at XXX.service.mq.consumer.implementation.ApacheMqConsumer.consume(ApacheMqConsumer.java:43)\n  at XXX.service.mq.consumer.core.ActiveMqConsumerHandler.processMessage(ActiveMqConsumerHandler.java:101)\n  at XXX.service.mq.consumer.core.ActiveMqConsumerHandler.runReceiveLoop(ActiveMqConsumerHandler.java:240)\n  at XXX.service.mq.consumer.core.ActiveMqConsumerHandler.startReceiving(ActiveMqConsumerHandler.java:206)\n  at XXX.service.mq.consumer.core.ActiveMqConsumerHandler.prepareConsumerAndStartReceiving(ActiveMqConsumerHandler.java:195)\n  at XXX.service.mq.consumer.core.ActiveMqConsumerHandler.startConnectionRunReceiver(ActiveMqConsumerHandler.java:180)\n  at XXX.service.mq.consumer.core.ActiveMqConsumerHandler.run(ActiveMqConsumerHandler.java:137)\n  at java.lang.Thread.run(Thread.java:748)"}
```

I hope that describes problem properly.

**Comment by ArtemProc** [comment]
@evilr00t in source code you can verify in_sudo_tail.rb - it does not have support for multiline format definition - so multiline does not suppose to work.
https://github.com/Microsoft/OMS-Agent-for-Linux/blob/master/source/code/plugins/in_sudo_tail.rb

1. You can create Custom conf file and do the monitoring with standard fluentd tail plugin.
2. You can check if one of delimiters based on Time Stamp can suite your needs.
https://docs.microsoft.com/en-us/azure/log-analytics/log-analytics-data-sources-custom-logs

**Comment by shpimpal** [comment]
closing this.
